name: Build HomeNetSentinel MT7621 IPK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Chmod scripts
        run: chmod +x build_ipk.sh

      - name: Create dummy binary
        run: |
          mkdir -p $HOME/.build/HomeNetSentinel/out-musl
          echo "#dummy" > $HOME/.build/HomeNetSentinel/out-musl/HomeNetSentinel
          chmod +x $HOME/.build/HomeNetSentinel/out-musl/HomeNetSentinel

            - name: Download MT7621 SDK
        run: |
          curl -L -o sdk.tar.zst \
            https://downloads.immortalwrt.org/releases/24.10.1/targets/ramips/mt7621/immortalwrt-sdk-24.10.1-ramips-mt7621_gcc-13.3.0_musl.Linux-x86_64.tar.zst \
            --retry 20 --retry-delay 10 --retry-all-errors \
            --connect-timeout 10 --max-time 300 -k
          
          tar -xf sdk.tar.zst -C $HOME/

          mv $HOME/immortalwrt-sdk-24.10.1-ramips-mt7621_gcc-13.3.0_musl.Linux-x86_64 \
             $HOME/immortalwrt-sdk-mt7621

      - name: Build IPK
        run: |
          ./build_ipk.sh \
            --bin "$HOME/.build/HomeNetSentinel/out-musl/HomeNetSentinel" \
            --arch mipsel_24kc \
            --version 1.0.0-0 \
            --output "$HOME/.build/ipk" \
            --ipkg-build "$HOME/immortalwrt-sdk-mt7621/scripts/ipkg-build"

      - name: Upload IPK
        uses: actions/upload-artifact@v4
        with:
          name: mt7621-ipk
          path: $HOME/.build/ipk/*.ipk
